file:
  storage:
    type: ${FILE_STORAGE_TYPE:local}
    local:
      base-path: ${LOCAL_STORAGE_BASE_PATH:./local-storage}
      base-url: ${LOCAL_STORAGE_BASE_URL:http://localhost:8080}
      upload-url-expiry-seconds: ${LOCAL_STORAGE_UPLOAD_URL_EXPIRY_SECONDS:600}
    s3:
      bucket: ${AWS_S3_BUCKET:}
      region: ${AWS_REGION:}
      upload-url-expiry-seconds: ${S3_UPLOAD_URL_EXPIRY_SECONDS:600}
